# Generated by Django 6.0.1 on 2026-02-01 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=50, verbose_name='Origem')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Data da Resposta')),
                ('location_name', models.CharField(max_length=255, verbose_name='Nome/ID Loja')),
                ('customer_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Cliente')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo')),
                ('score_general', models.IntegerField(blank=True, null=True, verbose_name='Nota Geral')),
                ('score_delivery', models.IntegerField(blank=True, null=True, verbose_name='Nota Entrega')),
                ('score_consultant', models.IntegerField(blank=True, null=True, verbose_name='Nota Consultor')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Comentário')),
            ],
        ),
    ]
